"""Init command - bootstrap Osiris from scratch."""

import logging
import os
import secrets
import shutil
import string
from pathlib import Path

import click

from osiris import systemd
from osiris.config import LoggingConfig
from osiris.env import is_production
from osiris.logging import setup_logging
from osiris.restic import Restic

# Default paths (used in production environment)
DEFAULT_PASSWORD_FILE = Path("/etc/osiris/repo-password")
DEFAULT_REPOSITORY = Path("/var/backups/osiris/repo")
DEFAULT_SSH_KEY = Path("/etc/osiris/ssh/id_ed25519")
DEFAULT_LOG_FILE = Path("/var/log/osiris/osiris.log")
DEFAULT_CACHE_DIR = Path("/var/cache/osiris")


def _get_paths(config_path: Path) -> dict:
    """
    Get paths for init based on environment.

    In production (OSIRIS_ENV=production or unset):
        Uses system paths like /etc/osiris/, /var/log/osiris/, etc.

    In development/test (OSIRIS_ENV=development or OSIRIS_ENV=test):
        Derives paths from config file directory for local testing.

    See docs/environment.md for details.
    """
    if is_production():
        # Production: use system paths
        return {
            "password_file": DEFAULT_PASSWORD_FILE,
            "ssh_dir": DEFAULT_SSH_KEY.parent,
            "ssh_key": DEFAULT_SSH_KEY,
            "log_file": DEFAULT_LOG_FILE,
            "cache_dir": DEFAULT_CACHE_DIR,
            "run_dir": Path("/run/osiris"),
        }
    else:
        # Development/test: use paths relative to config directory
        config_dir = config_path.parent
        return {
            "password_file": config_dir / "repo-password",
            "ssh_dir": config_dir / "ssh",
            "ssh_key": config_dir / "ssh" / "id_ed25519",
            "log_file": config_dir / "osiris.log",
            "cache_dir": config_dir / "cache",
            "run_dir": config_dir / "run",
        }


# Config template
DEFAULT_CONFIG_TEMPLATE = """\
# Osiris Backup Configuration
# Generated by 'osiris init'
# Edit this file to add your backup targets

repository: {repository}
password_file: {password_file}

logging:
  level: info
  file: {log_file}
  journal: true

ssh:
  user: osiris
  key_file: {ssh_key}
  control_master: true
  control_path: /run/osiris/ssh-%r@%h:%p
  control_persist: 300

# Add your backup targets here:
targets:
  # Example PostgreSQL target (uncomment and edit):
  # postgres:
  #   type: pg_dump
  #   host: postgres-01
  #   pg_user: postgres
  #   databases:
  #     - mydb
  #     - analytics

  # Example rsync target for MinIO (uncomment and edit):
  # minio:
  #   type: rsync
  #   host: minio-01
  #   path: /var/lib/minio/data

retention:
  keep_daily: 7
  keep_weekly: 4
  keep_monthly: 6
"""


@click.command()
@click.option(
    "--repository",
    default=str(DEFAULT_REPOSITORY),
    help="Path to restic repository",
    show_default=True,
)
@click.option(
    "--generate-password",
    is_flag=True,
    help="Generate a random password instead of prompting",
)
@click.option(
    "--force",
    is_flag=True,
    help="Overwrite existing configuration",
)
@click.pass_context
def init(ctx, repository: str, generate_password: bool, force: bool):
    """Initialize Osiris: create config, repository, and install systemd service."""
    ui = ctx.obj["ui"]
    config_path = Path(ctx.obj["config_path"])

    # Get paths based on config location
    paths = _get_paths(config_path)

    # Setup basic logging for init command (no file logging yet)
    logger = setup_logging(LoggingConfig(file=None, journal=False))

    # Step 1: Check if already initialized
    if config_path.exists() and not force:
        ui.error(f"Already initialized: {config_path}")
        ui.hint("Use --force to reinitialize (will overwrite config)")
        raise SystemExit(1)

    # Step 2: Get or generate password
    if generate_password:
        alphabet = string.ascii_letters + string.digits + "!@#$%^&*"
        password = "".join(secrets.choice(alphabet) for _ in range(32))
        ui.info("Generated random password")
    else:
        if not ui.interactive:
            ui.error("Cannot prompt for password in non-interactive mode")
            ui.hint("Use --generate-password to auto-generate")
            raise SystemExit(1)

        password = ui.prompt("Enter repository password", mask=True)
        confirm = ui.prompt("Confirm password", mask=True)

        if password != confirm:
            ui.error("Passwords do not match")
            raise SystemExit(1)

        if len(password) < 8:
            ui.warning("Password is very short (< 8 characters)")
            if not ui.confirm("Continue anyway?"):
                raise SystemExit(1)

    # Step 3: Create directory structure
    directories = [
        config_path.parent,  # config directory
        paths["ssh_dir"],  # SSH key directory
        paths["log_file"].parent,  # log directory
        paths["cache_dir"],  # cache directory
        Path(repository).parent,  # repository parent
        paths["run_dir"],  # SSH control sockets
    ]

    for directory in directories:
        try:
            directory.mkdir(parents=True, exist_ok=True)
        except PermissionError:
            ui.error(f"Permission denied creating: {directory}")
            ui.hint("Run as root: sudo osiris init")
            raise SystemExit(1)

    ui.success("Created directory structure")

    # Step 4: Create password file
    password_path = paths["password_file"]
    try:
        if password_path.exists() and not force:
            ui.error(f"Password file already exists: {password_path}")
            ui.hint("Use --force to overwrite")
            raise SystemExit(1)

        # Remove existing file if force
        if password_path.exists():
            password_path.unlink()

        fd = os.open(
            password_path,
            os.O_WRONLY | os.O_CREAT | os.O_EXCL,
            mode=0o400,
        )
        with os.fdopen(fd, "w") as f:
            f.write(password + "\n")

        ui.success(f"Created password file: {password_path}")
        logger.info(f"Created password file: {password_path}")

    except PermissionError:
        ui.error(f"Permission denied creating: {password_path}")
        ui.hint("Run as root: sudo osiris init")
        raise SystemExit(1)

    # Step 5: Create config file
    config_content = DEFAULT_CONFIG_TEMPLATE.format(
        repository=repository,
        password_file=str(paths["password_file"]),
        log_file=str(paths["log_file"]),
        ssh_key=str(paths["ssh_key"]),
    )

    try:
        config_path.write_text(config_content)
        ui.success(f"Created config file: {config_path}")
        logger.info(f"Created config file: {config_path}")
    except PermissionError:
        ui.error(f"Permission denied creating: {config_path}")
        raise SystemExit(1)

    # Step 6: Initialize restic repository
    if not shutil.which("restic"):
        ui.error("restic binary not found in PATH")
        ui.hint("Install restic: apt install restic")
        raise SystemExit(1)

    restic = Restic(repository, str(paths["password_file"]))

    if restic.is_initialized() and not force:
        ui.info(f"Repository already initialized: {repository}")
    else:
        try:
            ui.info(f"Initializing repository: {repository}")
            restic.init()
            ui.success(f"Initialized repository: {repository}")
            logger.info(f"Initialized repository: {repository}")
        except Exception as e:
            ui.error(f"Failed to initialize repository: {e}")
            raise SystemExit(1)

    # Step 7: Install systemd service and timer
    if systemd.is_systemd_available():
        try:
            if systemd.is_installed() and not force:
                ui.info("Systemd service already installed")
            else:
                systemd.install_service()
                ui.success("Installed systemd service")
                logger.info("Installed systemd service")

            if not systemd.is_enabled():
                systemd.enable_timer()
                ui.success("Enabled backup timer (daily at 2:00 AM)")
                logger.info("Enabled backup timer")
            else:
                ui.info("Backup timer already enabled")

        except PermissionError:
            ui.warning("Could not install systemd service (permission denied)")
            ui.hint("Run: sudo osiris service install")
        except Exception as e:
            ui.warning(f"Could not install systemd service: {e}")
    else:
        ui.info("Systemd not available, skipping service installation")

    # Step 8: Install logrotate config
    _install_logrotate_config(ui, logger, paths["log_file"])

    # Step 9: Show password if generated
    if generate_password:
        print()
        ui.warning("IMPORTANT: Save this password securely!")
        ui.info(f"Password: {password}")
        ui.hint("This is the only time the password will be displayed")

    # Step 10: Show next steps
    print()
    ui.success("Initialization complete!")
    print()
    ui.info("Next steps:")
    ui.info(f"  1. Edit {config_path} to add your backup targets")
    ui.info("  2. Run 'osiris validate' to test configuration")
    ui.info("  3. Run 'osiris backup --force' to test manually")


def _install_logrotate_config(ui, logger: logging.Logger, log_file: Path) -> None:
    """Install logrotate configuration for Osiris logs."""
    logrotate_path = Path("/etc/logrotate.d/osiris")
    logrotate_dir = logrotate_path.parent

    if not logrotate_dir.exists():
        ui.info("logrotate not installed, skipping")
        return

    if logrotate_path.exists():
        ui.info("Logrotate config already exists")
        return

    logrotate_content = f"""\
{log_file} {{
    weekly
    rotate 4
    compress
    delaycompress
    missingok
    notifempty
    create 0640 root root
}}
"""

    try:
        logrotate_path.write_text(logrotate_content)
        ui.success(f"Created logrotate config: {logrotate_path}")
        logger.info(f"Created logrotate config: {logrotate_path}")
    except PermissionError:
        ui.warning("Could not create logrotate config (permission denied)")
